### ISSUE TITLE
Dig doesn't work on naked domain

### ISSUE THREAD

**Issue by iiroj** [BotoX/dehydrated-cloudflare-hook#1]
The current commad for checking the challenge didn't work for me for `iiro.fi`:

    digresult="$(dig +short TXT _acme-challenge.${!idomain} +trace | grep '^TXT ' | awk '{ print substr($2, 2, length($2) - 2) }')"

This always resulted in:

    [CHALLENGE] Waiting for DNS: iiro.fi -> "" != "redacted"

I simplified the dig command to this and it started working for all my domains (including subdomains):

    digresult="$(dig +short TXT _acme-challenge.${!idomain} | tr -d \")"

**Comment by BotoX** [comment]
Yes, a friend of mine had the same issue with +trace that it took half an hour to work.
From my experience +trace works better because it queries the root DNS servers. But maybe some ISPs cache the response or god knows...
I guess it shouldn't hurt to remove the trace if you're having problems with it too.
